<script setup lang="ts">
import { onMounted } from 'vue'
import SoftwareCard from '../components/SoftwareCard.vue'
import { useScrollAnimation } from '../composables/useScrollAnimation'

interface Link {
  type: 'paper' | 'github' | 'preprint'
  url: string
  label: string
}

interface SoftwareItem {
  name: string
  description: string
  author?: string
  links: Link[]
  badge?: string
}

const softwareList: SoftwareItem[] = [
  {
    name: 'WASP',
    description:
      'WASP is a software package for unbiased allele-specific read mapping and molecular QTL discovery written by Bryce van de Geijn and Graham McVicker.',
    links: [
      { type: 'paper', url: '#', label: 'Paper' },
      { type: 'github', url: '#', label: 'GitHub' },
    ],
  },
  {
    name: 'WASP2',
    description:
      'WASP2 (under development) is the next generation of the WASP software for allele specific analysis. It currently provides filtering of reads with mapping biases, mapping, counting of allele-specific reads, and statistical tests for allelic imbalance. The interface has been greatly simplified and it is more computationally efficient than WASP. WASP2 is written by Aaron Ho.',
    badge: 'Under Development',
    links: [{ type: 'github', url: '#', label: 'GitHub' }],
  },
  {
    name: 'RELICS',
    description:
      'RELICS is a tool for the discovery of functional sequences from tiling CRISPR screens. RELICS was written by Patrick Fiaux.',
    author: 'Patrick Fiaux',
    links: [
      { type: 'paper', url: '#', label: 'Paper' },
      { type: 'github', url: '#', label: 'GitHub' },
    ],
  },
  {
    name: 'CRSsim',
    description:
      'CRSsim is a tool simulating data generated by CRISPR regulatory screens and assessing the performance of various analysis methods for analyzing CRISPR regulatory screens. CRSsim was written by Patrick Fiaux.',
    author: 'Patrick Fiaux',
    links: [
      { type: 'paper', url: '#', label: 'Paper' },
      { type: 'github', url: '#', label: 'GitHub' },
    ],
  },
  {
    name: 'VarCA',
    description:
      'VarCA is an ensembl method for the discovery of single nucleotide variants and indels from ATAC-seq reads. VarCA was written by Anja Massarat, based on some initial ideas developed in the BreakCA tool developed by Arko Sen.',
    author: 'Anja Massarat',
    links: [
      { type: 'paper', url: '#', label: 'Paper' },
      { type: 'github', url: '#', label: 'GitHub' },
    ],
  },
  {
    name: 'bkgd',
    description:
      'bkgd is a program for calculating B values across the genome. A B value is an estimate of the effect of background selection at a given site in the genome, given the recombination rate and density of sites under purifying selection.',
    links: [
      { type: 'paper', url: '#', label: 'Paper' },
      { type: 'github', url: '#', label: 'GitHub' },
    ],
  },
  {
    name: 'GLiMMIRS',
    description:
      'GLiMMIRS is a generalized linear model framework for identifying interactions between enhancers using single-cell CRISPR perturbation data. GLiMMIRS was written by Jessica Zhou and Karthik Guruvayurappan.',
    author: 'Jessica Zhou and Karthik Guruvayurappan',
    links: [
      { type: 'preprint', url: '#', label: 'Preprint' },
      { type: 'github', url: '#', label: 'GitHub' },
    ],
  },
]

const { fadeInUp, staggerFadeInUp } = useScrollAnimation()

onMounted(() => {
  fadeInUp('.animate-title')
  fadeInUp('.animate-description')
  staggerFadeInUp('.animate-card')
})
</script>

<template>
  <main class="max-w-7xl mx-auto px-6 py-12">
    <h1 class="animate-title text-4xl font-light text-gray-800 mb-4">Software</h1>
    <p class="animate-description text-gray-600 mb-12 max-w-3xl">
      Open-source tools and software packages developed by the McVicker Lab for genomic analysis,
      allele-specific mapping, and CRISPR screen analysis.
    </p>

    <!-- Software Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div class="animate-card" v-for="(software, index) in softwareList" :key="index">
        <SoftwareCard :software="software" />
      </div>
    </div>
  </main>
</template>

<style scoped></style>
